name: Pixi Dev Update
on:
  repository_dispatch:
    types: [update-dev]
jobs:
  UpdateDev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
